services:
  - type: web
    name: crypto-terminal-x
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn terminal:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
